name: meeting_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  meeting_flutter:
    path: ../
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  universal_platform: any

flutter:
  uses-material-design: true
